<script lang="ts">
	import { Header } from '$lib/components/layout';

	const checklists = [
		{
			slug: 'pre-launch',
			title: 'Pre-Launch Security Checklist',
			description: 'Essential security checks before deploying your app to production.',
			items: 12,
			time: '30 min',
			audience: 'All developers'
		},
		{
			slug: 'api-security',
			title: 'API Security Checklist',
			description: 'Secure your REST and GraphQL APIs against common attacks.',
			items: 15,
			time: '45 min',
			audience: 'Backend developers'
		},
		{
			slug: 'authentication',
			title: 'Authentication Checklist',
			description: 'Properly implement user login, sessions, and access control.',
			items: 10,
			time: '25 min',
			audience: 'Full-stack developers'
		},
		{
			slug: 'database-security',
			title: 'Database Security Checklist',
			description: 'Protect your database from injection, leaks, and unauthorized access.',
			items: 8,
			time: '20 min',
			audience: 'Backend developers'
		},
		{
			slug: 'frontend-security',
			title: 'Frontend Security Checklist',
			description: 'XSS prevention, CSP headers, and client-side security.',
			items: 9,
			time: '25 min',
			audience: 'Frontend developers'
		},
		{
			slug: 'ai-code-review',
			title: 'AI-Generated Code Review Checklist',
			description: 'What to check when reviewing code generated by AI tools.',
			items: 11,
			time: '30 min',
			audience: 'All developers'
		}
	];
</script>

<svelte:head>
	<title>Security Checklists | VibeShip</title>
	<meta name="description" content="Actionable security checklists for developers. Pre-launch, API, authentication, database, and AI code review checklists." />
	<meta property="og:title" content="Security Checklists | VibeShip" />
	<meta property="og:description" content="Actionable security checklists for developers. Pre-launch, API, authentication, database, and AI code review checklists." />
	<meta property="og:url" content="/kb/checklists/" />
	<meta property="og:type" content="website" />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="Security Checklists | VibeShip" />
	<meta name="twitter:description" content="Actionable security checklists for developers. Pre-launch, API, authentication, database, and AI code review checklists." />
	<link rel="canonical" href="https://vibeship.co/kb/checklists/" />
</svelte:head>

<Header breadcrumbs={[
	{ label: 'Knowledge Base', href: '/kb' },
	{ label: 'Checklists' }
]} />

<div class="content-wrapper">
	<div class="content-main content-wide">
		<div class="article-header">
			<h1>Security Checklists</h1>
			<p class="text-secondary" style="font-size: 1.1rem; max-width: 650px;">
				Actionable checklists you can run through before shipping. Each item links to detailed explanations and fix prompts.
			</p>
		</div>

		<div class="quick-answer">
			<div class="quick-answer-label">
				<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
					<path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/>
				</svg>
				Start Here
			</div>
			<p class="quick-answer-text">
				New to security? Start with the <strong>Pre-Launch Security Checklist</strong>. It covers the most critical items every app needs before going live.
			</p>
		</div>

		<div class="stats-row">
			<div class="stat-box">
				<div class="stat-value">6</div>
				<div class="stat-label">checklists</div>
			</div>
			<div class="stat-box">
				<div class="stat-value">65+</div>
				<div class="stat-label">check items</div>
			</div>
			<div class="stat-box">
				<div class="stat-value">~3hrs</div>
				<div class="stat-label">total review time</div>
			</div>
			<div class="stat-box">
				<div class="stat-value">Free</div>
				<div class="stat-label">and open</div>
			</div>
		</div>

		<section class="article-section">
			<h2>All Checklists</h2>
			<div class="checklist-grid">
				{#each checklists as checklist}
					<a href="/kb/checklists/{checklist.slug}" class="card card-interactive checklist-card">
						<h3>{checklist.title}</h3>
						<p>{checklist.description}</p>
						<div class="checklist-meta">
							<div class="checklist-stat">
								<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
									<path d="M9 11l3 3L22 4"/>
									<path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/>
								</svg>
								{checklist.items} items
							</div>
							<div class="checklist-stat">
								<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
									<circle cx="12" cy="12" r="10"/>
									<path d="M12 6v6l4 2"/>
								</svg>
								{checklist.time}
							</div>
						</div>
						<div class="checklist-audience">
							<span class="audience-label">For:</span>
							<span class="audience-value">{checklist.audience}</span>
						</div>
					</a>
				{/each}
			</div>
		</section>

		<section class="article-section">
			<h2>How to Use Checklists</h2>
			<ol>
				<li><strong>Pick the right checklist:</strong> Choose based on your role and what you're building</li>
				<li><strong>Work through each item:</strong> Don't skip items even if they seem obvious</li>
				<li><strong>Use linked resources:</strong> Each item links to explanations and fix prompts</li>
				<li><strong>Run automated checks:</strong> Use <a href="https://scanner.vibeship.co">Vibeship Scanner</a> for automatic detection</li>
			</ol>
		</section>

		<section class="article-section">
			<h2>Checklist by Role</h2>
			<div class="role-grid">
				<div class="role-card">
					<h3>Frontend Developer</h3>
					<ul>
						<li><a href="/kb/checklists/frontend-security">Frontend Security Checklist</a></li>
						<li><a href="/kb/checklists/ai-code-review">AI Code Review Checklist</a></li>
					</ul>
				</div>
				<div class="role-card">
					<h3>Backend Developer</h3>
					<ul>
						<li><a href="/kb/checklists/api-security">API Security Checklist</a></li>
						<li><a href="/kb/checklists/database-security">Database Security Checklist</a></li>
						<li><a href="/kb/checklists/authentication">Authentication Checklist</a></li>
					</ul>
				</div>
				<div class="role-card">
					<h3>Full-Stack / Solo Dev</h3>
					<ul>
						<li><a href="/kb/checklists/pre-launch">Pre-Launch Checklist</a> (start here)</li>
						<li>All other checklists as needed</li>
					</ul>
				</div>
			</div>
		</section>
	</div>
</div>

<style>
	.checklist-grid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
		gap: 1rem;
		margin-top: 1.5rem;
	}

	.checklist-card {
		text-decoration: none;
		color: inherit;
	}

	.checklist-card:hover {
		text-decoration: none;
	}

	.checklist-card h3 {
		margin: 0 0 0.5rem;
		font-size: 1.1rem;
		color: var(--text-primary);
	}

	.checklist-card p {
		margin: 0 0 1rem;
		font-size: 0.85rem;
		color: var(--text-secondary);
		line-height: 1.5;
	}

	.checklist-meta {
		display: flex;
		gap: 1.25rem;
		margin-bottom: 0.75rem;
	}

	.checklist-stat {
		display: flex;
		align-items: center;
		gap: 0.35rem;
		font-size: 0.8rem;
		color: var(--text-tertiary);
	}

	.checklist-stat svg {
		color: var(--text-tertiary);
	}

	.checklist-audience {
		padding-top: 0.75rem;
		border-top: 1px solid var(--border);
		display: flex;
		gap: 0.5rem;
		font-size: 0.8rem;
	}

	.audience-label {
		color: var(--text-tertiary);
	}

	.audience-value {
		color: var(--text-secondary);
	}

	.role-grid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
		gap: 1rem;
		margin-top: 1rem;
	}

	.role-card {
		background: var(--bg-secondary);
		border: 1px solid var(--border);
		padding: 1.25rem;
	}

	.role-card h3 {
		margin: 0 0 0.75rem;
		font-size: 1rem;
		color: var(--text-primary);
	}

	.role-card ul {
		margin: 0;
		padding-left: 1.25rem;
	}

	.role-card li {
		margin-bottom: 0.35rem;
		font-size: 0.85rem;
	}

	.role-card a {
		color: var(--green-dim);
	}

	.role-card a:hover {
		color: var(--green);
	}
</style>
